version: "3"
services:
  reverseproxy:
      image: gehadhamdy/udagram-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed    
      environment:
        API_HOST: api
        NODE_ENV: development   
  backend-user:
    image: gehadhamdy/udagram-api-user
    environment:
      AWS_ACESS_KEY: $AWS_ACESS_KEY
      SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: gehadhamdy/udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      AWS_ACESS_KEY: $AWS_ACESS_KEY
      SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: gehadhamdy/udagram-frontend
    ports:
      - "8100:80"