version: "3"
services:
  reverseproxy:
      image: gehadhamdy/udagram-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: gehadhamdy/udagram-api-user
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456789 
      POSTGRES_DB: postgres 
      POSTGRES_HOST: udagram.czdw0fvhi9rw.us-east-1.rds.amazonaws.com 
      AWS_REGION: us-east-1 
      AWS_PROFILE: default 
      AWS_ACESS_KEY: AKIATHNE4YF3ISVA6GH6
      SWCRET_ACCESS_KEY: RN8+6JvSzoFSttlFYQYBFExB3ccXNQgsUStBmPN4
      AWS_BUCKET: udagram-222073504118
      JWT_SECRET: testing
      URL: "http://a8ef659ec34e749a1a012cd1dc7bfd4a-1904095924.us-east-1.elb.amazonaws.com:8100"
  backend-feed:
    image: gehadhamdy/udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456789 
      POSTGRES_DB: postgres 
      POSTGRES_HOST: udagram.czdw0fvhi9rw.us-east-1.rds.amazonaws.com 
      AWS_REGION: us-east-1
      AWS_PROFILE: default 
      AWS_ACESS_KEY: AKIATHNE4YF3ISVA6GH6
      SWCRET_ACCESS_KEY: RN8+6JvSzoFSttlFYQYBFExB3ccXNQgsUStBmPN4
      AWS_BUCKET: udagram-222073504118
      JWT_SECRET: testing
      URL: "http://a8ef659ec34e749a1a012cd1dc7bfd4a-1904095924.us-east-1.elb.amazonaws.com:8100"
  frontend:
    image: gehadhamdy/udagram-frontend:local
    ports:
      - "8100:80"