version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: gehadhamdy/udagram-reverseproxy
  backend_user:
    build:
      context: ../udagram-api-user
    image: gehadhamdy/udagram-api-user
  backend_feed:
    build:
      context: ../udagram-api-feed 
    image: gehadhamdy/udagram-api-feed
  frontend:
    build:
      context: ../udagram-frontend
    image: gehadhamdy/udagram-frontend