apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reverseproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reverseproxy
    spec:
      containers:
      - image: gehadhamdy/udagram-reverseproxy:latest
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"    
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: NODE_ENV    
        ports:
        - containerPort: 8080
      restartPolicy: Always